site_name: VR on Linux
site_url: https://vr-on-linux.gitlab.io/
repo_url: https://gitlab.com/vr-on-linux/VR-on-Linux
repo_name: VR on Linux repository
site_dir: public
site_description: Documenting the status of VR/AR software and hardware on Linux
site_author: yaomtc
copyright: Copyright Creative Commons Attribution-ShareAlike 4.0 International

nav:
  - '👍 VR Database - User Reviews': 'https://db.vronlinux.org/'
  - '🏠 Native/Supported Titles': index.md
  - '⚙️ Modding Skyrim VR': SkyrimVRModding.md
  - '🛠️ Contributing': CONTRIBUTING.md

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

theme:
  name: 'material'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo: assets/icon.png
  favicon: assets/icon.png
  scheme: slate
  features:
    - search.highlight
    - search.share
    - header.autohide
    - announce.dismiss

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'light blue'
      accent: 'light green'
      toggle:
        icon: material/weather-sunny
        name: Toogle light mode
    - media: "(prefers-color-scheme: light)"
      scheme: light
      primary: 'blue grey'
      accent: 'light green'
      toggle:
        icon: material/weather-night
        name: Toggle dark mode

extra:
  social:
    - icon: 'fontawesome/brands/gitlab'
      link: 'https://gitlab.com/vr-on-linux/VR-on-Linux'
    - icon: 'fontawesome/brands/steam'
      link: 'https://steamcommunity.com/sharedfiles/filedetails/?id=2984005943'
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/VR-on-Linux/VR-on-Linux'

extra_css:
  - stylesheets/extra.css
